Collections:
  - Name: Pix2seq
    Metadata:
      Training Data: COCO
      Training Techniques:
        - AdamW
        - Multi Scale Train
        - Gradient Clip
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - Transformer
    Paper:
      URL: https://arxiv.org/abs/2109.10852
      Title: 'Pix2seq: A Language Modeling Framework for Object Detection'
    README: configs/pix2seq/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.7.0/mmdet/models/detectors/pix2seq.py
      Version: v1.0.0

Models:
  - Name: pix2seq_r50_4x2_50e_coco
    In Collection: Pix2seq
    Config: configs/pix2seq/pix2seq_r50_4x2_50e_coco.py
    Metadata:
      Training Memory (GB): 7.9
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.0
    Weights: https://drive.google.com/file/d/1Ku8ZORiLtMs66uleS3aXId7pxlJrTK9d/view?usp=sharing
